### ISSUE TITLE
Feature request: A title field describing a dataset

### ISSUE THREAD

**Issue by tomsing1** [iSEE/iSEEindex#32]
It would be great to have separate `title` and `description` files to annotate a dataset. The former could e.g. be shown in the table users can select individual datasets from. The latter would then be shown on the right when a user has selected one dataset. The `description` could then hold HTML, e.g. URLs with links to additional information. In contrast, the `title` should only be plain text for display in the table.

We could think of other annotation elements, e.g. tags as well. But having both a short `title` and a longer `description` would go a long way, especially if the latter can capture multiple pieces of information.

**Comment by kevinrue** [comment]
That's essentially what `label` and `description` are intended for. `label` is the `title` that you mention, while `description` does exactly what you describe. I was only showing `description` in the table so that there were at least two columns. I'll remove `description` from the table and only show it in the right panel.

**Comment by tomsing1** [comment]
Ah yes! Sorry, I missed the label field.

**Comment by kevinrue** [comment]
I'll rename `label` to `title` , it's probably clearer.

**Comment by kevinrue** [comment]
Fixed by #33

**Comment by kevinrue** [comment]
PR merged
